name: Auto-merge bot PRs

on: 
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
    prbot:
        runs-on: ubuntu-latest
        steps:
          - name: Enable auto-merge for bot PRs
            run: gh pr merge --auto --merge "$PR_URL"
            env:
              PR_URL: ${{github.event.pull_request.html_url}}
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
