on:
  push:
    branches:
    - dev

jobs:
  test:
    name: Test on py ${{ matrix.py }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py: ['3.11']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }} 
    - name: Install pip
      run:
        python -m pip install --upgrade pip
    - name: Install deps
      run: 
        python -m pip install poetry poethepoet tox
    - name: Test with poe/tox
      run: poe validate

  pull-request:
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      always() && 
      (needs.test.result == 'success')
    steps:
    - uses: actions/checkout@v4
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
        destination_branch: "main"