on:
  push:
    branches:
    - dev

jobs:
  test_on_py_os_marix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py: ['3.11']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py }} 
    - name: Install pip
      run:
        python -m pip install --upgrade pip
    - name: Install deps
      run: 
        python -m pip install poetry poethepoet tox
    - name: Test with poe/tox
      run: poe validate

  pull-request:
    runs-on: ubuntu-latest
    needs: [test_on_py_os_marix]
    if: |
      always() && 
      (needs.test_on_py_os_marix.result == 'success')
    steps:
    - uses: actions/checkout@v4
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
        destination_branch: "main"

  alls-green:
    if: always()

    needs:
    - test_on_py_os_marix
    - pull-request

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}